### PR TITLE
Restructure codebase, add small test suite, return a NetworkX representation of the graph

### PR DESCRIPTION
**Pull request by fedarko**
Hi! I ended up needing a python FASTG parser for [a project I'm working on](https://github.com/marbl/MetagenomeScope), so I went and made a few changes to your library to make it suit my needs (thanks for putting it on GitHub :).

A few of the major changes:

- Returns a [NetworkX](http://networkx.github.io/) DiGraph, useful for further analysis (see README for example uses)
- Fixed a small bug where, if the final outgoing neighbor node of a node was a reverse-complement (e.g. node `5` in `>EDGE_6_length_81_cov_26.75:EDGE_1_length_9909_cov_6.94721,EDGE_5_length_4847_cov_6.51132';`), that node would not be treated as a reverse-complement node (since its "declaration" [seemingly ends in `;` and not `'`](https://github.com/nickp60/pyfastg/blob/0533be11e2d02358e12445cc6ab9b2022a9f67f3/pyfastg.py#L38))
- Added a decently thorough test suite. Could stand to be more detailed, but it at least covers all of the code now.
  - Added `.travis.yml` and set up Travis-CI and CodeCov integration (see https://travis-ci.org/fedarko/pyfastg, https://codecov.io/gh/fedarko/pyfastg)
  - Set up automatic style-checking/linting (see the Makefile)
- Simplified a lot of the code structure (the `FastgNode` and `FastgNodeNeighbor` classes have been replaced with just storing node information in the NetworkX DiGraph)
- Keep track of node sequences (only for one node at a time, to save on memory), and use these sequences to compute GC-content for each node (uses [scikit-bio](http://skbio.org) to do this)
- Added a `setup.py` file (pyfastg is now pip installable, and could ostensibly be uploaded to PyPI)

I know these are some pretty drastic changes, and that it's been a while since you put this online! So no worries if you don't have time to review this :) I think this library fulfills a really useful niche (at least for people working in python + sequence assembly), and hopefully these changes make interpreting SPAdes/etc. output much easier for python programmers.

### CODE REVIEW

**Comment by nickp60** [comment]
Hi @fedarko !  Wow, this looks fantastic! I don't really have the bandwidth to continue maintaining this (as you can probably tell from the history!), but I think with your changes this could definitely be more widely useful. Would you be up for taking control over this? I'd be happy to transfer ownership to you...

**Comment by fedarko** [comment]
@nickp60 Thanks for the kind words! I'm hesitant to say I can maintain this indefinitely, but I'd be happy to at least take charge of this for the short-term (fixing bugs that come up, making the package available on PyPI, etc.), as long as you're ok with it. This is code that I would've had to write for my project anyway, so I'm fine with that :)

One question: do you have a preferred license for this code? That's probably something we should sort out before uploading it to PyPI.

**Comment by nickp60** [comment]
Sounds Good, I'll pass it over! I don't have wrong feelings regarding license; I usually use MIT just for simplicity, but I'm fine with anything permissive and open.  Maybe MIT or GPL3?

**Comment by fedarko** [comment]
Cool! I feel the same way; either of those licenses sounds like a good choice (my vote is for MIT, but I'll leave it up to you). Thanks!

**Comment by nickp60** [comment]
Great, I have added the MIT License -- would you mind deleting (or renaming) your fork?  I can't transfer ownership if you already have a `fedarko/pyfastg` repo

**Comment by fedarko** [comment]
Ah, sorry about that! Deleted my fork.

**Pull request merged**
